### ISSUE TITLE
JFrog Plugin Integration Showing All Components Instead of Specific Artifact

### ISSUE THREAD

**Issue by BanerjeeAgniva** [Vity01/backstage-jfrog-artifactory-libs#13]
After adding JFrog integration details in the `catalog-info.yaml` file, _all components from the repository are displayed instead of only the expected artifact_. The integration should filter and display only the specific artifact mentioned in the configuration.

**Expected Behavior :**

Only the specified artifact should appear in the catalog view, not all components from the repository.

**Steps to Reproduce :**

Add the following configuration to `catalog-info.yaml`:
```
[jfrog.com/artifactory-artifact](http://jfrog.com/artifactory-artifact) : "sample-nodejs-lambda"
[jfrog.com/artifactory-group](http://jfrog.com/artifactory-group): "SAMPLE-GROUP"
[jfrog.com/artifactory-repo](http://jfrog.com/artifactory-repo): "SAMPLE-REPO"
```
2. Save and push the configuration.
3. Navigate to the JFrog integration section in the catalog.
4. Observe that all components appear instead of the specified artifact.

**Actual Behavior :**

Instead of only showing `sample-nodejs-lambda`, all artifacts from the repository appear.

**Impact :**

Affects usability as users cannot filter JFrog artifacts properly in the catalog.

**Environment:**

Module: JFrog Integration in Catalog
Browser: Chrome

**Additional Context:**

It seems like the filtering mechanism for JFrog integration is not correctly applying the catalog-info.yaml specifications. This needs to be investigated to ensure proper artifact filtering.

**Comment by Vity01** [comment]
It seems to me you have probably bad file structure in your repository or something. 
Check this GraphQL query... https://github.com/Vity01/backstage-jfrog-artifactory-libs/blob/main/src/components/LibArtifactCard/api.ts#L95

**Comment by BanerjeeAgniva** [comment]
> It seems to me you have probably bad file structure in your repository or something. Check this GraphQL query... https://github.com/Vity01/backstage-jfrog-artifactory-libs/blob/main/src/components/LibArtifactCard/api.ts#L95

<img width="1438" alt="Image" src="https://github.com/user-attachments/assets/ab54a0e2-72d8-479a-bb32-1b7e08d2d190" />

I am using the harness-public repo here 

<img width="961" alt="Image" src="https://github.com/user-attachments/assets/34fa86b9-d409-48d7-9237-417a6e9ddf3d" />

and I have configured the app-config.yaml as 

```
proxy:
  endpoints:
    /artifactory-proxy/:
      target: https://harness.jfrog.io
      pathRewrite:
        api/proxy/artifactory-proxy/?: /
      headers:
        Authorization: Bearer ${ARTIFACTORY_TOKEN}
        X-Result-Detail: properties
        Accept: "*"
jfrog:
  artifactory:
    url: https://harness.jfrog.io/ui
    proxyPath: /artifactory-proxy/

```

and the catalog that I have registered has these jfrog details : 

```
    jfrog.com/artifactory-group: io.harness.cv
    jfrog.com/artifactory-artifact: data-collection-dsl-0.26-RELEASE.jar
    jfrog.com/artifactory-repo: harness-public
```


Artifact Count / Size: | 189 / 20.83 MB (harness-public) 

but still :

<img width="1405" alt="Image" src="https://github.com/user-attachments/assets/d838e846-5566-4809-a4e6-79d451450612" />
